[package]
name = "advent2016"
version = "0.1.0"
authors = ["Mike Mueller <mike@subfocal.net>"]

[dependencies]
argparse = ""
error-chain = "0.7"
lazy_static = ""
rand = ""
regex = "0.1"
rust-crypto = ""
